# Generated by Django 3.1.1 on 2020-10-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='image',
            field=models.FileField(default='some_value', upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='sku',
            field=models.CharField(default='some_value', max_length=100),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='stock',
            field=models.BooleanField(max_length=25),
        ),
    ]
