# Generated by Django 3.1.1 on 2020-10-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanpham',
            name='id',
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='image',
            field=models.ImageField(upload_to='%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='sku',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
