# Generated by Django 3.1.1 on 2020-10-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_auto_20201025_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='brief',
            field=models.TextField(max_length=150),
        ),
    ]
